FROM node:20-alpine AS builder
WORKDIR /app
COPY shared ./shared
COPY server ./server
COPY package.json .
RUN npm install
RUN npm run build -w @vault/shared
RUN npm run build -w @vault/server

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/server/dist ./dist
COPY --from=builder /app/server/prisma ./prisma
COPY --from=builder /app/server/package.json .
COPY --from=builder /app/node_modules ./node_modules
RUN npx prisma generate
EXPOSE 4000
CMD ["node", "dist/index.js"]
