FROM node:20-alpine AS builder
WORKDIR /app
COPY client ./client
COPY package.json .
RUN npm install
RUN npm run build -w @vault/client

FROM nginx:alpine AS runner
COPY --from=builder /app/client/dist /usr/share/nginx/html
COPY client/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
